name: Tests

on:
  push:          # run on all branches when you push
  pull_request:  # run on all PRs, regardless of target branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run pytest with coverage
        run: |
          uv run pytest --cov=src/ibproxy --cov-report=term-missing --cov-fail-under=90

      - name: Run pytest with coverage (XML)
        run: |
          uv run pytest --cov=src/ibproxy --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
